# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='mypictures/%Y/%m/%d')),
                ('content', models.CharField(max_length=10000)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
