# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytext',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='mytext',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
