# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180412_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytext',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
    ]
