# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 09:18
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mytext_likes_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True),
        ),
    ]
