# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180416_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
